### ISSUE TITLE
apriltag_docking

### ISSUE THREAD

**Issue by hydraplus2** [Adlink-ROS/apriltag_docking#2]
Hello, I tried following the steps to installing the dependencies, but when I use rosdep install there was an error with the rosdep keys, like this:

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
apriltag_docking: Cannot locate rosdep definition for [cmake_modules]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully

does anyone know how to fix this?

**Comment by Bread2018** [comment]
I have the same problem, do you fix it?

**Comment by QQting** [comment]
Hi,

Actually, the error won't affect the compilation and program execution.
And you won't see the error anymore because I've removed the cmake_modules from packages.xml.
Check https://github.com/Adlink-ROS/apriltag_docking/commit/d66c169cf88a0b9e7c207acc8609d16b3ad07a1f

Ting
